// Code generated by "stringer -type=FlightState"; DO NOT EDIT.

package adsbexchange

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Parking-1]
	_ = x[Taxing-2]
	_ = x[Enroute-3]
}

const _FlightState_name = "UnknownParkingTaxingEnroute"

var _FlightState_index = [...]uint8{0, 7, 14, 20, 27}

func (i FlightState) String() string {
	if i < 0 || i >= FlightState(len(_FlightState_index)-1) {
		return "FlightState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FlightState_name[_FlightState_index[i]:_FlightState_index[i+1]]
}
