aircaftData: "http://downloads.adsbexchange.com/downloads/basic-ac-db.json.gz"
updateAircraftDataInterval: 1
updateAircraftFlightInformationInterval: 5
aircraftRegistrations: ac-registration
observerInterval: 10
observerFile: observationList
